export const animalPropertyProperNames = {
  // id: 'ID',
  type: 'Type',
  name: 'Name',
  breed: 'Breed',
  // tagNumber: 'Tag #',
  // registrationnumber: 'Registration #',
  birthDate: 'Birth Date',
  purchaseDate: 'Purchase Date',
  // cost: 'Cost',
  // neutered: 'Intact',
  // neuteredDate: 'Neutered Date',
  // deathDate: 'Died',
  // cull: 'Cull',
  // sold: 'Sold',
  // soldTo: 'Sold To',
  // salePrice: 'Sale Price',
  // saleDate: 'Sale Date',
  // auctionSale: 'Auction Sale',
  // auctionName: 'Auction Name',
  // auctionWeight: 'Auction Weight',
  // sire: 'Sire',
  // dam: 'Dam',
  // damSire: 'Dam-Sire',
  // breeder: 'Breeder',
  // notes: 'Notes',
  // birthWeight: 'Birth Weight',
  herd: 'Herd',
  herdId: 'Herd Id',
  ownerId: 'Owner',
};
